/*
 * Autogenerated by program
 * Author YKMoon
 * Do not edit unless you are sure that you know what you are doning
*/
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using System.IO;

namespace YKMoon.SDKTools.Editor
{
    internal partial class UPMUtility
    {
        public static string packageName => string.Format("com.{0}.{1}", "ykmoon", "sdktools");
        public static string packageResPath => string.Format("Packages/{0}/Res/Editor", packageName);

        public static string packagePrefabPath => string.Format("Packages/{0}/Res/Editor/Prefabs", packageName);
        /// <summary>
        /// Instantiate Prefab in res path
        /// </summary>
        /// <param name="path">path under EditorRes/Prefabs</param>
        /// <returns></returns>
        public static GameObject InstantiatePresetPrefab(string path)
        {
            GameObject obj = AssetDatabase.LoadAssetAtPath<GameObject>(packagePrefabPath + "/" + path + ".prefab");
            var result = GameObject.Instantiate(obj);
            return result;
        }
    }
}